version: '3.8'
services:
  api:
    image: your_dockerhub_username/your_image_name:latest
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app:ro
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - MAIL_PORT=587
      - MAIL_SERVER=smtp.gmail.com
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      - POSTGRES_DB: ${DATABASE_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: